### ISSUE TITLE
Allow @API annotation for packages

### ISSUE THREAD

**Issue by jlink** [apiguardian-team/apiguardian#21] opened 2021-01-05 07:38 UTC
Sometimes a whole package could profit of an API annotation.  Please add `ElementType.PACKAGE` as allowed target.

**Comment by marcphilipp** [comment] 2021-01-05 07:45
This was done in #20 and released in 1.1.1

**Comment by marcphilipp** [comment] 2021-01-05 07:45
Duplicate of #19

**Closed by marcphilipp** 2021-01-05 07:45 UTC
